@startuml MLD
class Utilisateur{
    # email : string,
    password : hash,
    nom : string,
    prenom : string,
    date_naissance : date,
    - date_creation : date,
    - statut : bool,
    telephone : string,
    adresse_utilisateur_lat : float,
    adresse_utilisateur_long : float,
    sexe : SEXE,
    type_utilisateur : TYPE_UTILISATEUR
}

class Formulaire{
    #id : int,
    etat_formulaire : ETAT,
    date_creation : date,
    type_formulaire : TYPE_FORMULAIRE,
    email_utilisateur : string => Utilisateur.email
    siren_orga : string => Organisation.siren
}

class Organisation{
    #siren : string,
    nom : string,
    siege_social_lat : float,
    siege_social_long : float,
    type_organisation : string => Type_organisation.nom
}

class Type_organisation{
    #nom : string,
    description : string
}

class  Candidature{
    #id : int,
    date_candidature : date,
    etat : ETAT,
    email_utilisateur : string => Utilisateur.email,
    id_offre : int => Offre_d_emploi.id
}

class Pieces_jointes {
    #id : int,
    nom : string,
    type : TYPE_PIECE,
    lien : string,
    id_candidature : int => Candidature.id
}

class Offre_d_emploi{
    #id : int,
    nombre_de_piece : unsigned int,
    etat : ETAT_OFFRE,
    date_validite : date,
    indication_piece_jointes : string,
    id_poste : int => Fiche_poste.id
}

class Fiche_poste{
    #numero : int,
    intitule : string,
    responsable_hierarchique : string,
    lieu_mission_lat : float,
    lieu_mission_long : float,
    rythme : string,
    salaire_min : float,
    salaire_max : float,
    statut_poste : string => Statut_poste.nom
    type_metier : string => Type_metier.nom
}

class Type_metier{
    #nom : string,
    description : string
}

class Statut_poste{
    #nom : string,
    description : string
}

class Description{
    #numero : int => Fiche_poste.numero,
    missions : string,
    acrtivités : string,
    competences_attendues : string
}
@enduml